"""Create table ThirdParty authentication

Revision ID: 9fb23c089e3e
Revises: ce8e664d111d
Create Date: 2021-09-23 18:17:11.794099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fb23c089e3e'
down_revision = 'ce8e664d111d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('third_party_authentication',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('google_uid', sa.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_third_party_authentication_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'user_id', name=op.f('pk_third_party_authentication'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('third_party_authentication')
    # ### end Alembic commands ###
