"""New base of clients attributes

Revision ID: d1cc32f7df77
Revises: 87d224564651
Create Date: 2021-10-24 14:29:56.520454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1cc32f7df77'
down_revision = '87d224564651'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_attribute',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('attribute_key', sa.VARCHAR(length=255), nullable=False),
    sa.Column('attribute_value', sa.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name=op.f('fk_client_attribute_client_id_client'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_attribute'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_attribute')
    # ### end Alembic commands ###
