"""Return password in user model

Revision ID: 3ac479e4b371
Revises: b7ea6a4f10cc
Create Date: 2021-12-29 08:15:38.478534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ac479e4b371'
down_revision = 'b7ea6a4f10cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=255), nullable=True))
    op.execute("UPDATE public.\"user\" SET password = 'qwerty'")
    op.alter_column('user', 'password', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
