"""Create participants model

Revision ID: b7ea6a4f10cc
Revises: edd77097cbad
Create Date: 2021-11-01 09:10:45.458777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7ea6a4f10cc'
down_revision = 'edd77097cbad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participant',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('client_email', sa.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name=op.f('fk_participant_client_id_client'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['calendar_event.id'], name=op.f('fk_participant_event_id_calendar_event'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_participant'))
    )
    op.drop_constraint('fk_calendar_event_client_id_client', 'calendar_event', type_='foreignkey')
    op.drop_column('calendar_event', 'client_id')
    op.drop_column('calendar_event', 'client_email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_event', sa.Column('client_email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('calendar_event', sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_calendar_event_client_id_client', 'calendar_event', 'client', ['client_id'], ['id'], ondelete='CASCADE')
    op.drop_table('participant')
    # ### end Alembic commands ###
