"""Create event calendar table

Revision ID: edd77097cbad
Revises: fb67cb8309ee
Create Date: 2021-10-28 09:04:42.234465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edd77097cbad'
down_revision = 'fb67cb8309ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('event_description', sa.VARCHAR(length=1024), nullable=False),
    sa.Column('event_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('event_from_time', sa.TIME(), nullable=False),
    sa.Column('event_to_time', sa.TIME(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('client_email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], name=op.f('fk_calendar_event_business_id_business'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name=op.f('fk_calendar_event_client_id_client'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_calendar_event_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calendar_event'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calendar_event')
    # ### end Alembic commands ###
