"""Change settings foregn key business role

Revision ID: 87d224564651
Revises: 5791d8c7459b
Create Date: 2021-10-13 09:28:32.875897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87d224564651'
down_revision = '5791d8c7459b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_team_member_role_id_role_permissions', 'team_member', type_='foreignkey')
    op.create_foreign_key(op.f('fk_team_member_role_id_business_roles'), 'team_member', 'business_roles', ['role_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_team_member_role_id_business_roles'), 'team_member', type_='foreignkey')
    op.create_foreign_key('fk_team_member_role_id_role_permissions', 'team_member', 'role_permissions', ['role_id'], ['id'], ondelete='SET DEFAULT')
    # ### end Alembic commands ###
