"""Reform model business

Revision ID: 5791d8c7459b
Revises: 6f2642823372
Create Date: 2021-10-01 12:53:16.788415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5791d8c7459b'
down_revision = '6f2642823372'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scope_type_business',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.String(length=3000), nullable=False),
    sa.Column('hide', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scope_type_business'))
    )
    op.add_column('business', sa.Column('scope_type_id', sa.Integer(), nullable=True))
    op.add_column('business', sa.Column('type_business', sa.Enum('INDIVIDUAL', 'LLC', 'SOLE_PROPRIETOR', name='usertypeforbusiness', native_enum=False), nullable=False))
    op.create_foreign_key(op.f('fk_business_scope_type_id_scope_type_business'), 'business', 'scope_type_business', ['scope_type_id'], ['id'], ondelete='SET DEFAULT')
    op.drop_column('business', 'type_business_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('type_business_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_business_scope_type_id_scope_type_business'), 'business', type_='foreignkey')
    op.drop_column('business', 'type_business')
    op.drop_column('business', 'scope_type_id')
    op.drop_table('scope_type_business')
    # ### end Alembic commands ###
