"""Add email in team member

Revision ID: fb67cb8309ee
Revises: d1cc32f7df77
Create Date: 2021-10-26 09:02:00.258863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb67cb8309ee'
down_revision = 'd1cc32f7df77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_member', sa.Column('email', sa.VARCHAR(length=255), nullable=True))
    op.execute("UPDATE team_member SET email = ''")
    op.alter_column('team_member', 'email', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_member', 'email')
    # ### end Alembic commands ###
