"""Delete unique of phone

Revision ID: d7296b2bec91
Revises: 4276b8e6525f
Create Date: 2021-09-27 11:00:30.954864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7296b2bec91'
down_revision = '4276b8e6525f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_phone', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_phone', 'user', ['phone'])
    # ### end Alembic commands ###
